# vim:set ft=tmux:

# --> Solarized (dark)
set -ogq @thm_bg "#073642"
set -ogq @thm_fg "#fdf6e3"

# Colors
set -ogq @thm_rosewater "#eee8d5"
set -ogq @thm_flamingo "#eee8d5"
set -ogq @thm_pink "#d33682"
set -ogq @thm_mauve "#6c71c4"
set -ogq @thm_red "#dc322f"
set -ogq @thm_maroon "#d33682"
set -ogq @thm_peach "#cb4b16"
set -ogq @thm_yellow "#b58900"
set -ogq @thm_green "#859900"
set -ogq @thm_teal "#2aa198"
set -ogq @thm_sky "#2aa198"
set -ogq @thm_sapphire "#268bd2"
set -ogq @thm_blue "#268bd2"
set -ogq @thm_lavender "#6c71c4"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#93a1a1"
set -ogq @thm_subtext_0 "#839496"
set -ogq @thm_overlay_2 "#839496"
set -ogq @thm_overlay_1 "#657b83"
set -ogq @thm_overlay_0 "#586e75"
set -ogq @thm_surface_2 "#073642"
set -ogq @thm_surface_1 "#073642"
set -ogq @thm_surface_0 "#002b36"
set -ogq @thm_mantle "#073642"
set -ogq @thm_crust "#002b36"

