# vim:set ft=tmux:
# --> Tokyo Night (moon)
set -ogq @thm_bg "#222436"
set -ogq @thm_fg "#c8d3f5"

# Colors
set -ogq @thm_rosewater "#c8d3f5"
set -ogq @thm_flamingo "#ff757f"
set -ogq @thm_pink "#ff007c"
set -ogq @thm_mauve "#c099ff"
set -ogq @thm_red "#ff757f"
set -ogq @thm_maroon "#c53b53"
set -ogq @thm_peach "#ff966c"
set -ogq @thm_yellow "#ffc777"
set -ogq @thm_green "#c3e88d"
set -ogq @thm_teal "#4fd6be"
set -ogq @thm_sky "#86e1fc"
set -ogq @thm_sapphire "#0db9d7"
set -ogq @thm_blue "#82aaff"
set -ogq @thm_lavender "#fca7ea"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#c8d3f5"
set -ogq @thm_subtext_0 "#828bb8"
set -ogq @thm_overlay_2 "#7a88cf"
set -ogq @thm_overlay_1 "#737aa2"
set -ogq @thm_overlay_0 "#545c7e"
set -ogq @thm_surface_2 "#444a73"
set -ogq @thm_surface_1 "#3b4261"
set -ogq @thm_surface_0 "#2f334d"
set -ogq @thm_mantle "#1e2030"
set -ogq @thm_crust "#14151f"
