# screen-style prefix key
set -g prefix C-a

# last window
bind-key C-a last-window

# Start window numbering at 1
set -g base-index 1

# Renumber all windows when one is closed
set -g renumber-windows on

# move status bar to top
set-option -g status-position bottom

# turn on mouse support
set -g mouse on

# hjkl pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

## git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'aaronpowell/tmux-weather'
# C-a I will then install those plugins

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# theme stuff that should probably be seperated out
set -g @tmux-gruvbox 'dark' # dark dark256, light, light256
set -g @tmux-gruvbox-right-status-x '%Y/%m/%d T %H:%M'
set -g @tmux-gruvbox-right-status-y ' '
set -g @forecast-format '%c+%t+%w'
run '~/.tmux/plugins/tpm/tpm'
