# screen-style prefix key
set -g prefix C-a

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Allows for faster key repetition
set -s escape-time 10

# last window
bind-key C-a last-window

# Start window numbering at 1
set -g base-index 1

# Renumber all windows when one is closed
set -g renumber-windows on

# move status bar to top
set-option -g status-position bottom

# hjkl pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

## git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
# C-a I will then install those plugins

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -g default-terminal "tmux-256color"

# Enable 24-bit true color support
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-features ",tmux-256color:RGB"

# Enable true color overrides for terminal capabilities
set -ga terminal-overrides ",xterm-256color:Tc"
set -ga terminal-overrides ",tmux-256color:Tc"
set -ga terminal-overrides ",*256col*:Tc"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "macchiato"
source-file ~/.tmux/plugins/tmux/themes/catppuccin_gruvbox_tmux.conf
set -g @catppuccin_window_status_style "rounded"

set -g @catppuccin_window_text " #W#{?window_zoomed_flag,(󰛭),}"
set -g @catppuccin_window_default_text " #W#{?window_zoomed_flag,(󰛭),}"
set -g @catppuccin_window_current_text " #W#{?window_zoomed_flag,(󰛭),}"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left '#{E:@catppuccin_status_session} '
set -g @catppuccin_session_icon " "
set -gF status-right ""
set -ag status-right '#{E:@catppuccin_status_date_time}'

run '~/.tmux/plugins/tpm/tpm'
