# screen-style prefix key
set -g prefix C-a

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# last window
bind-key C-a last-window

# Start window numbering at 1
set -g base-index 1

# Renumber all windows when one is closed
set -g renumber-windows on

# move status bar to top
set-option -g status-position bottom

# hjkl pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

## git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux#v2.3.0'
#set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'aaronpowell/tmux-weather'
#set -g @plugin 'xamut/tmux-weather'
set -g @plugin 'ilya-manin/tmux-weather'
# C-a I will then install those plugins

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# this should give us better colours
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# weather config
set -g @forecast-location Sutton+Park,+Sault+Ste+Marie
set -g @forecast-format '%c+%t+%w'

## theme stuff that should probably be seperated out
#set -g @tmux-gruvbox 'dark' # dark dark256, light, light256
#set -g @tmux-gruvbox-right-status-x '%Y/%m/%d T %H:%M'
#set -g @tmux-gruvbox-right-status-y ' '
##this does weird stuff... to do with the symbol?
##set -g @tmux-gruvbox-right-status-z '#{forecast}'


# Configure the catppuccin plugin
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "slanted"
#Left Status
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"
#Right
set -g status-right-length 100
set -g status-right "#{E:@catppuccin_status_directory}"
set-option -g @tmux-weather-location "Tomsk"
set-option -g @tmux-weather-format "%c+%t+%w"
set-option -g @tmux-weather-unit "m"
set -agF status-right "#{E:@catppuccin_status_weather} "

set -ag status-right "asdf#{weather} asdf"
set -ag status-right "#{E:@catppuccin_status_date_time}"

# nice zoom indicator, but it's not working
#set -g window-status-format " #I:#W#{?window_zoomed_flag, ,}"
#set -g window-status-current-format " #I:#W#{?window_zoomed_flag, ,}"





run '~/.tmux/plugins/tpm/tpm'
