" Colorscheme generated by https://github.com/arcticlimer/djanho
highlight clear

function s:highlight(group, bg, fg, style)
  let gui = a:style == '' ? '' : 'gui=' . a:style
  let fg = a:fg == '' ? '' : 'guifg=' . a:fg
  let bg = a:bg == '' ? '' : 'guibg=' . a:bg
  exec 'hi ' . a:group . ' ' . bg . ' ' . fg  . ' ' . gui
endfunction

let s:Color12 = '#062e32'
let s:Color5 = '#d5971a'
let s:Color18 = '#40d4e7'
let s:Color9 = '#e3541c'
let s:Color13 = '#08423b'
let s:Color1 = '#b2cacd'
let s:Color6 = '#49e9a6'
let s:Color15 = '#0a4c53'
let s:Color10 = '#052629'
let s:Color0 = '#5b858b'
let s:Color16 = '#4e6b6e'
let s:Color8 = '#16a3b6'
let s:Color11 = '#169fb1'
let s:Color17 = '#87a7ab'
let s:Color3 = '#e4b781'
let s:Color14 = '#3f3c32'
let s:Color4 = '#d67e5c'
let s:Color2 = '#df769b'
let s:Color7 = '#7060eb'

call s:highlight('Comment', '', s:Color0, '')
call s:highlight('TSCharacter', '', s:Color1, '')
call s:highlight('Keyword', '', s:Color2, '')
call s:highlight('Conditional', '', s:Color2, '')
call s:highlight('Repeat', '', s:Color2, '')
call s:highlight('Identifier', '', s:Color3, '')
call s:highlight('Type', '', s:Color4, '')
call s:highlight('Constant', '', s:Color5, '')
call s:highlight('String', '', s:Color6, '')
call s:highlight('Number', '', s:Color7, '')
call s:highlight('Function', '', s:Color8, '')
call s:highlight('Error', '', s:Color9, '')
call s:highlight('Comment', '', '', 'italic')
call s:highlight('Keyword', '', '', 'bold')
call s:highlight('Operator', '', '', 'bold')
call s:highlight('Conditional', '', '', 'bold')
call s:highlight('Repeat', '', '', 'bold')
call s:highlight('StatusLine', s:Color11, s:Color10, '')
call s:highlight('WildMenu', s:Color12, s:Color1, '')
call s:highlight('Pmenu', s:Color12, s:Color1, '')
call s:highlight('PmenuSel', s:Color1, s:Color12, '')
call s:highlight('PmenuThumb', s:Color12, s:Color1, '')
call s:highlight('DiffAdd', s:Color13, '', '')
call s:highlight('DiffDelete', s:Color14, '', '')
call s:highlight('Normal', s:Color12, s:Color1, '')
call s:highlight('Visual', s:Color15, '', '')
call s:highlight('CursorLine', s:Color15, '', '')
call s:highlight('ColorColumn', s:Color15, '', '')
call s:highlight('SignColumn', s:Color12, '', '')
call s:highlight('LineNr', '', s:Color16, '')
call s:highlight('TabLine', s:Color12, s:Color17, '')
call s:highlight('TabLineSel', s:Color18, s:Color12, '')
call s:highlight('TabLineFill', s:Color12, s:Color17, '')
call s:highlight('TSPunctDelimiter', '', s:Color1, '')

highlight! link TSKeyword Keyword
highlight! link TSConstant Constant
highlight! link TSPunctSpecial TSPunctDelimiter
highlight! link TSRepeat Repeat
highlight! link TSParameterReference TSParameter
highlight! link TSNumber Number
highlight! link CursorLineNr Identifier
highlight! link TSFloat Number
highlight! link Operator Keyword
highlight! link TSFunction Function
highlight! link TSField Constant
highlight! link TSConditional Conditional
highlight! link TSString String
highlight! link TSNamespace TSType
highlight! link TelescopeNormal Normal
highlight! link Repeat Conditional
highlight! link TSTag MyTag
highlight! link TSComment Comment
highlight! link TSLabel Type
highlight! link TSPunctBracket MyTag
highlight! link NonText Comment
highlight! link TSFuncMacro Macro
highlight! link TSTagDelimiter Type
highlight! link TSProperty TSField
highlight! link TSType Type
highlight! link TSConstBuiltin TSVariableBuiltin
highlight! link Folded Comment
highlight! link Whitespace Comment
highlight! link Macro Function
highlight! link TSParameter Constant
highlight! link Conditional Operator
highlight! link TSOperator Operator
