" Colorscheme generated by https://github.com/arcticlimer/djanho
highlight clear

function s:highlight(group, bg, fg, style)
  let gui = a:style == '' ? '' : 'gui=' . a:style
  let fg = a:fg == '' ? '' : 'guifg=' . a:fg
  let bg = a:bg == '' ? '' : 'guibg=' . a:bg
  exec 'hi ' . a:group . ' ' . bg . ' ' . fg  . ' ' . gui
endfunction

let s:Color14 = '#d1ebc8'
let s:Color16 = '#d8edeb'
let s:Color2 = '#ff5792'
let s:Color8 = '#0095a8'
let s:Color10 = '#0099ad'
let s:Color0 = '#8ca6a6'
let s:Color9 = '#ff530f'
let s:Color11 = '#f0e9d6'
let s:Color12 = '#005661'
let s:Color1 = '#004d57'
let s:Color5 = '#a88c00'
let s:Color15 = '#f5dbcd'
let s:Color17 = '#a0abac'
let s:Color7 = '#5842ff'
let s:Color13 = '#fef8ec'
let s:Color18 = '#888477'
let s:Color3 = '#fa8900'
let s:Color4 = '#b3694d'
let s:Color6 = '#00b368'

call s:highlight('Comment', '', s:Color0, '')
call s:highlight('TSCharacter', '', s:Color1, '')
call s:highlight('Keyword', '', s:Color2, '')
call s:highlight('Conditional', '', s:Color2, '')
call s:highlight('Repeat', '', s:Color2, '')
call s:highlight('Identifier', '', s:Color3, '')
call s:highlight('Type', '', s:Color4, '')
call s:highlight('Constant', '', s:Color5, '')
call s:highlight('String', '', s:Color6, '')
call s:highlight('Number', '', s:Color7, '')
call s:highlight('Function', '', s:Color8, '')
call s:highlight('Error', '', s:Color9, '')
call s:highlight('Comment', '', '', 'italic')
call s:highlight('Keyword', '', '', 'bold')
call s:highlight('Operator', '', '', 'bold')
call s:highlight('Conditional', '', '', 'bold')
call s:highlight('Repeat', '', '', 'bold')
call s:highlight('StatusLine', s:Color10, s:Color11, '')
call s:highlight('WildMenu', s:Color13, s:Color12, '')
call s:highlight('Pmenu', s:Color13, s:Color12, '')
call s:highlight('PmenuSel', s:Color12, s:Color13, '')
call s:highlight('PmenuThumb', s:Color13, s:Color12, '')
call s:highlight('DiffAdd', s:Color14, '', '')
call s:highlight('DiffDelete', s:Color15, '', '')
call s:highlight('Normal', s:Color13, s:Color12, '')
call s:highlight('Visual', s:Color16, '', '')
call s:highlight('CursorLine', s:Color16, '', '')
call s:highlight('ColorColumn', s:Color16, '', '')
call s:highlight('SignColumn', s:Color13, '', '')
call s:highlight('LineNr', '', s:Color17, '')
call s:highlight('TabLine', s:Color11, s:Color18, '')
call s:highlight('TabLineSel', s:Color10, s:Color13, '')
call s:highlight('TabLineFill', s:Color11, s:Color18, '')
call s:highlight('TSPunctDelimiter', '', s:Color12, '')

highlight! link TSConditional Conditional
highlight! link TSKeyword Keyword
highlight! link TSPunctBracket MyTag
highlight! link TSTag MyTag
highlight! link TSTagDelimiter Type
highlight! link TelescopeNormal Normal
highlight! link TSOperator Operator
highlight! link Conditional Operator
highlight! link TSLabel Type
highlight! link Macro Function
highlight! link TSParameter Constant
highlight! link Repeat Conditional
highlight! link TSParameterReference TSParameter
highlight! link TSString String
highlight! link TSField Constant
highlight! link CursorLineNr Identifier
highlight! link TSProperty TSField
highlight! link TSComment Comment
highlight! link TSNumber Number
highlight! link TSRepeat Repeat
highlight! link Operator Keyword
highlight! link TSConstant Constant
highlight! link TSType Type
highlight! link Folded Comment
highlight! link TSPunctSpecial TSPunctDelimiter
highlight! link TSConstBuiltin TSVariableBuiltin
highlight! link NonText Comment
highlight! link TSFunction Function
highlight! link TSFloat Number
highlight! link Whitespace Comment
highlight! link TSFuncMacro Macro
highlight! link TSNamespace TSType
