" Colorscheme generated by https://github.com/arcticlimer/djanho
highlight clear

function s:highlight(group, bg, fg, style)
  let gui = a:style == '' ? '' : 'gui=' . a:style
  let fg = a:fg == '' ? '' : 'guifg=' . a:fg
  let bg = a:bg == '' ? '' : 'guibg=' . a:bg
  exec 'hi ' . a:group . ' ' . bg . ' ' . fg  . ' ' . gui
endfunction

let s:Color9 = '#e3541c'
let s:Color10 = '#8767a8'
let s:Color8 = '#16a3b6'
let s:Color1 = '#ccbfd9'
let s:Color4 = '#d67e5c'
let s:Color11 = '#30243d'
let s:Color12 = '#2c3a45'
let s:Color15 = '#665973'
let s:Color17 = '#b3a5c0'
let s:Color18 = '#bf8ef1'
let s:Color7 = '#7060eb'
let s:Color13 = '#5e343a'
let s:Color5 = '#d5971a'
let s:Color3 = '#e4b781'
let s:Color2 = '#df769b'
let s:Color0 = '#7f659a'
let s:Color14 = '#4d3a60'
let s:Color16 = '#3d2e4d'
let s:Color6 = '#49e9a6'

call s:highlight('Comment', '', s:Color0, '')
call s:highlight('TSCharacter', '', s:Color1, '')
call s:highlight('Keyword', '', s:Color2, '')
call s:highlight('Conditional', '', s:Color2, '')
call s:highlight('Repeat', '', s:Color2, '')
call s:highlight('Identifier', '', s:Color3, '')
call s:highlight('Type', '', s:Color4, '')
call s:highlight('Constant', '', s:Color5, '')
call s:highlight('String', '', s:Color6, '')
call s:highlight('Number', '', s:Color7, '')
call s:highlight('Function', '', s:Color8, '')
call s:highlight('Error', '', s:Color9, '')
call s:highlight('Comment', '', '', 'italic')
call s:highlight('Keyword', '', '', 'bold')
call s:highlight('Operator', '', '', 'bold')
call s:highlight('Conditional', '', '', 'bold')
call s:highlight('Repeat', '', '', 'bold')
call s:highlight('StatusLine', s:Color10, s:Color11, '')
call s:highlight('WildMenu', s:Color11, s:Color1, '')
call s:highlight('Pmenu', s:Color11, s:Color1, '')
call s:highlight('PmenuSel', s:Color1, s:Color11, '')
call s:highlight('PmenuThumb', s:Color11, s:Color1, '')
call s:highlight('DiffAdd', s:Color12, '', '')
call s:highlight('DiffDelete', s:Color13, '', '')
call s:highlight('Normal', s:Color11, s:Color1, '')
call s:highlight('Visual', s:Color14, '', '')
call s:highlight('CursorLine', s:Color14, '', '')
call s:highlight('ColorColumn', s:Color14, '', '')
call s:highlight('SignColumn', s:Color11, '', '')
call s:highlight('LineNr', '', s:Color15, '')
call s:highlight('TabLine', s:Color16, s:Color17, '')
call s:highlight('TabLineSel', s:Color18, s:Color11, '')
call s:highlight('TabLineFill', s:Color16, s:Color17, '')
call s:highlight('TSPunctDelimiter', '', s:Color1, '')

highlight! link TSKeyword Keyword
highlight! link TSLabel Type
highlight! link TSPunctBracket MyTag
highlight! link TSProperty TSField
highlight! link Macro Function
highlight! link CursorLineNr Identifier
highlight! link TSRepeat Repeat
highlight! link TSString String
highlight! link TSConstBuiltin TSVariableBuiltin
highlight! link TSParameter Constant
highlight! link TSPunctSpecial TSPunctDelimiter
highlight! link TSNamespace TSType
highlight! link TelescopeNormal Normal
highlight! link TSFloat Number
highlight! link Repeat Conditional
highlight! link TSFuncMacro Macro
highlight! link Conditional Operator
highlight! link Whitespace Comment
highlight! link NonText Comment
highlight! link TSTagDelimiter Type
highlight! link TSType Type
highlight! link TSParameterReference TSParameter
highlight! link TSConstant Constant
highlight! link TSFunction Function
highlight! link TSTag MyTag
highlight! link TSNumber Number
highlight! link TSField Constant
highlight! link TSComment Comment
highlight! link Operator Keyword
highlight! link Folded Comment
highlight! link TSOperator Operator
highlight! link TSConditional Conditional
