" Colorscheme generated by https://github.com/arcticlimer/djanho
highlight clear

function s:highlight(group, bg, fg, style)
  let gui = a:style == '' ? '' : 'gui=' . a:style
  let fg = a:fg == '' ? '' : 'guifg=' . a:fg
  let bg = a:bg == '' ? '' : 'guibg=' . a:bg
  exec 'hi ' . a:group . ' ' . bg . ' ' . fg  . ' ' . gui
endfunction

let s:Color6 = '#00b368'
let s:Color8 = '#0095a8'
let s:Color5 = '#a88c00'
let s:Color0 = '#9995b7'
let s:Color15 = '#d5d1f1'
let s:Color12 = '#f2f1f8'
let s:Color13 = '#c8e6d2'
let s:Color17 = '#75718e'
let s:Color3 = '#fa8900'
let s:Color1 = '#0c006b'
let s:Color10 = '#e2dff6'
let s:Color9 = '#ff530f'
let s:Color14 = '#ead5d7'
let s:Color11 = '#7060eb'
let s:Color4 = '#b3694d'
let s:Color16 = '#9d9ab1'
let s:Color2 = '#ff5792'
let s:Color7 = '#5842ff'

call s:highlight('Comment', '', s:Color0, '')
call s:highlight('TSCharacter', '', s:Color1, '')
call s:highlight('Keyword', '', s:Color2, '')
call s:highlight('Conditional', '', s:Color2, '')
call s:highlight('Repeat', '', s:Color2, '')
call s:highlight('Identifier', '', s:Color3, '')
call s:highlight('Type', '', s:Color4, '')
call s:highlight('Constant', '', s:Color5, '')
call s:highlight('String', '', s:Color6, '')
call s:highlight('Number', '', s:Color7, '')
call s:highlight('Function', '', s:Color8, '')
call s:highlight('Error', '', s:Color9, '')
call s:highlight('Comment', '', '', 'italic')
call s:highlight('Keyword', '', '', 'bold')
call s:highlight('Operator', '', '', 'bold')
call s:highlight('Conditional', '', '', 'bold')
call s:highlight('Repeat', '', '', 'bold')
call s:highlight('StatusLine', s:Color11, s:Color10, '')
call s:highlight('WildMenu', s:Color12, s:Color1, '')
call s:highlight('Pmenu', s:Color12, s:Color1, '')
call s:highlight('PmenuSel', s:Color1, s:Color12, '')
call s:highlight('PmenuThumb', s:Color12, s:Color1, '')
call s:highlight('DiffAdd', s:Color13, '', '')
call s:highlight('DiffDelete', s:Color14, '', '')
call s:highlight('Normal', s:Color12, s:Color1, '')
call s:highlight('Visual', s:Color15, '', '')
call s:highlight('CursorLine', s:Color15, '', '')
call s:highlight('ColorColumn', s:Color15, '', '')
call s:highlight('SignColumn', s:Color12, '', '')
call s:highlight('LineNr', '', s:Color16, '')
call s:highlight('TabLine', s:Color10, s:Color17, '')
call s:highlight('TabLineSel', s:Color11, s:Color12, '')
call s:highlight('TabLineFill', s:Color10, s:Color17, '')
call s:highlight('TSPunctDelimiter', '', s:Color1, '')

highlight! link TSFunction Function
highlight! link TSType Type
highlight! link TSParameterReference TSParameter
highlight! link TSConditional Conditional
highlight! link Conditional Operator
highlight! link TSNamespace TSType
highlight! link Whitespace Comment
highlight! link TSField Constant
highlight! link Repeat Conditional
highlight! link NonText Comment
highlight! link TSProperty TSField
highlight! link TSNumber Number
highlight! link TSComment Comment
highlight! link Macro Function
highlight! link TSRepeat Repeat
highlight! link TSPunctBracket MyTag
highlight! link TSOperator Operator
highlight! link TSParameter Constant
highlight! link TelescopeNormal Normal
highlight! link TSPunctSpecial TSPunctDelimiter
highlight! link TSKeyword Keyword
highlight! link CursorLineNr Identifier
highlight! link TSLabel Type
highlight! link TSFloat Number
highlight! link TSFuncMacro Macro
highlight! link TSConstant Constant
highlight! link Operator Keyword
highlight! link TSString String
highlight! link TSTagDelimiter Type
highlight! link TSConstBuiltin TSVariableBuiltin
highlight! link Folded Comment
highlight! link TSTag MyTag
