" Colorscheme generated by https://github.com/arcticlimer/djanho
highlight clear

function s:highlight(group, bg, fg, style)
  let gui = a:style == '' ? '' : 'gui=' . a:style
  let fg = a:fg == '' ? '' : 'guifg=' . a:fg
  let bg = a:bg == '' ? '' : 'guibg=' . a:bg
  exec 'hi ' . a:group . ' ' . bg . ' ' . fg  . ' ' . gui
endfunction

let s:Color0 = '#5b858b'
let s:Color9 = '#e3541c'
let s:Color10 = '#169fb1'
let s:Color15 = '#4e6b6e'
let s:Color4 = '#d67e5c'
let s:Color5 = '#d5971a'
let s:Color13 = '#3c281e'
let s:Color8 = '#16a3b6'
let s:Color12 = '#052c25'
let s:Color1 = '#b2cacd'
let s:Color2 = '#df769b'
let s:Color7 = '#7060eb'
let s:Color17 = '#87a7ab'
let s:Color11 = '#031417'
let s:Color14 = '#083940'
let s:Color18 = '#ebfdff'
let s:Color16 = '#062e32'
let s:Color6 = '#49e9a6'
let s:Color3 = '#e4b781'

call s:highlight('Comment', '', s:Color0, '')
call s:highlight('TSCharacter', '', s:Color1, '')
call s:highlight('Keyword', '', s:Color2, '')
call s:highlight('Conditional', '', s:Color2, '')
call s:highlight('Repeat', '', s:Color2, '')
call s:highlight('Identifier', '', s:Color3, '')
call s:highlight('Type', '', s:Color4, '')
call s:highlight('Constant', '', s:Color5, '')
call s:highlight('String', '', s:Color6, '')
call s:highlight('Number', '', s:Color7, '')
call s:highlight('Function', '', s:Color8, '')
call s:highlight('Error', '', s:Color9, '')
call s:highlight('Comment', '', '', 'italic')
call s:highlight('Keyword', '', '', 'bold')
call s:highlight('Operator', '', '', 'bold')
call s:highlight('Conditional', '', '', 'bold')
call s:highlight('Repeat', '', '', 'bold')
call s:highlight('StatusLine', s:Color10, s:Color11, '')
call s:highlight('WildMenu', s:Color11, s:Color1, '')
call s:highlight('Pmenu', s:Color11, s:Color1, '')
call s:highlight('PmenuSel', s:Color1, s:Color11, '')
call s:highlight('PmenuThumb', s:Color11, s:Color1, '')
call s:highlight('DiffAdd', s:Color12, '', '')
call s:highlight('DiffDelete', s:Color13, '', '')
call s:highlight('Normal', s:Color11, s:Color1, '')
call s:highlight('Visual', s:Color14, '', '')
call s:highlight('CursorLine', s:Color14, '', '')
call s:highlight('ColorColumn', s:Color14, '', '')
call s:highlight('SignColumn', s:Color11, '', '')
call s:highlight('LineNr', '', s:Color15, '')
call s:highlight('TabLine', s:Color16, s:Color17, '')
call s:highlight('TabLineSel', s:Color18, s:Color11, '')
call s:highlight('TabLineFill', s:Color16, s:Color17, '')
call s:highlight('TSPunctDelimiter', '', s:Color1, '')

highlight! link TSRepeat Repeat
highlight! link TSNamespace TSType
highlight! link TSFloat Number
highlight! link CursorLineNr Identifier
highlight! link TSParameter Constant
highlight! link TSFunction Function
highlight! link TSConstBuiltin TSVariableBuiltin
highlight! link TelescopeNormal Normal
highlight! link TSField Constant
highlight! link TSLabel Type
highlight! link NonText Comment
highlight! link TSOperator Operator
highlight! link Macro Function
highlight! link Operator Keyword
highlight! link TSConditional Conditional
highlight! link TSProperty TSField
highlight! link TSNumber Number
highlight! link TSPunctBracket MyTag
highlight! link TSString String
highlight! link TSConstant Constant
highlight! link TSType Type
highlight! link TSTag MyTag
highlight! link Whitespace Comment
highlight! link TSComment Comment
highlight! link TSTagDelimiter Type
highlight! link TSKeyword Keyword
highlight! link Folded Comment
highlight! link Conditional Operator
highlight! link TSParameterReference TSParameter
highlight! link TSFuncMacro Macro
highlight! link TSPunctSpecial TSPunctDelimiter
highlight! link Repeat Conditional
