" Colorscheme generated by https://github.com/arcticlimer/djanho
highlight clear

function s:highlight(group, bg, fg, style)
  let gui = a:style == '' ? '' : 'gui=' . a:style
  let fg = a:fg == '' ? '' : 'guifg=' . a:fg
  let bg = a:bg == '' ? '' : 'guibg=' . a:bg
  exec 'hi ' . a:group . ' ' . bg . ' ' . fg  . ' ' . gui
endfunction

let s:Color7 = '#7060eb'
let s:Color4 = '#d67e5c'
let s:Color5 = '#d5971a'
let s:Color12 = '#093c43'
let s:Color9 = '#e3541c'
let s:Color3 = '#e4b781'
let s:Color1 = '#becfda'
let s:Color10 = '#07273b'
let s:Color18 = '#49ace9'
let s:Color17 = '#09334e'
let s:Color2 = '#df769b'
let s:Color14 = '#0c4264'
let s:Color8 = '#16a3b6'
let s:Color16 = '#9fb6c6'
let s:Color11 = '#1679b6'
let s:Color6 = '#49e9a6'
let s:Color13 = '#3f3638'
let s:Color0 = '#5988a6'
let s:Color15 = '#4d6c80'

call s:highlight('Comment', '', s:Color0, '')
call s:highlight('TSCharacter', '', s:Color1, '')
call s:highlight('Keyword', '', s:Color2, '')
call s:highlight('Conditional', '', s:Color2, '')
call s:highlight('Repeat', '', s:Color2, '')
call s:highlight('Identifier', '', s:Color3, '')
call s:highlight('Type', '', s:Color4, '')
call s:highlight('Constant', '', s:Color5, '')
call s:highlight('String', '', s:Color6, '')
call s:highlight('Number', '', s:Color7, '')
call s:highlight('Function', '', s:Color8, '')
call s:highlight('Error', '', s:Color9, '')
call s:highlight('Comment', '', '', 'italic')
call s:highlight('Keyword', '', '', 'bold')
call s:highlight('Operator', '', '', 'bold')
call s:highlight('Conditional', '', '', 'bold')
call s:highlight('Repeat', '', '', 'bold')
call s:highlight('StatusLine', s:Color11, s:Color10, '')
call s:highlight('WildMenu', s:Color10, s:Color1, '')
call s:highlight('Pmenu', s:Color10, s:Color1, '')
call s:highlight('PmenuSel', s:Color1, s:Color10, '')
call s:highlight('PmenuThumb', s:Color10, s:Color1, '')
call s:highlight('DiffAdd', s:Color12, '', '')
call s:highlight('DiffDelete', s:Color13, '', '')
call s:highlight('Normal', s:Color10, s:Color1, '')
call s:highlight('Visual', s:Color14, '', '')
call s:highlight('CursorLine', s:Color14, '', '')
call s:highlight('ColorColumn', s:Color14, '', '')
call s:highlight('SignColumn', s:Color10, '', '')
call s:highlight('LineNr', '', s:Color15, '')
call s:highlight('TabLine', s:Color17, s:Color16, '')
call s:highlight('TabLineSel', s:Color18, s:Color10, '')
call s:highlight('TabLineFill', s:Color17, s:Color16, '')
call s:highlight('TSPunctDelimiter', '', s:Color1, '')

highlight! link CursorLineNr Identifier
highlight! link TSType Type
highlight! link TSConditional Conditional
highlight! link TSOperator Operator
highlight! link TSLabel Type
highlight! link TSPunctSpecial TSPunctDelimiter
highlight! link TelescopeNormal Normal
highlight! link NonText Comment
highlight! link TSProperty TSField
highlight! link TSNamespace TSType
highlight! link TSTag MyTag
highlight! link TSRepeat Repeat
highlight! link Whitespace Comment
highlight! link Operator Keyword
highlight! link TSParameterReference TSParameter
highlight! link TSPunctBracket MyTag
highlight! link Folded Comment
highlight! link TSFunction Function
highlight! link TSString String
highlight! link TSConstant Constant
highlight! link TSFuncMacro Macro
highlight! link Repeat Conditional
highlight! link TSNumber Number
highlight! link Macro Function
highlight! link TSParameter Constant
highlight! link TSFloat Number
highlight! link TSField Constant
highlight! link TSTagDelimiter Type
highlight! link TSKeyword Keyword
highlight! link TSComment Comment
highlight! link Conditional Operator
highlight! link TSConstBuiltin TSVariableBuiltin
