# vim:set ft=tmux:
# --> Tokyo Night (day)
set -ogq @thm_bg "#e1e2e7"
set -ogq @thm_fg "#3760bf"

# Colors
set -ogq @thm_rosewater "#3760bf"
set -ogq @thm_flamingo "#f52a65"
set -ogq @thm_pink "#d20065"
set -ogq @thm_mauve "#9854f1"
set -ogq @thm_red "#f52a65"
set -ogq @thm_maroon "#c64343"
set -ogq @thm_peach "#b15c00"
set -ogq @thm_yellow "#8c6c3e"
set -ogq @thm_green "#587539"
set -ogq @thm_teal "#118c74"
set -ogq @thm_sky "#007197"
set -ogq @thm_sapphire "#07879d"
set -ogq @thm_blue "#2e7de9"
set -ogq @thm_lavender "#7847bd"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#6172b0"
set -ogq @thm_subtext_0 "#68709a"
set -ogq @thm_overlay_2 "#a1a6c5"
set -ogq @thm_overlay_1 "#8990b3"
set -ogq @thm_overlay_0 "#848cb5"
set -ogq @thm_surface_2 "#c4c8da"
set -ogq @thm_surface_1 "#b4b5b9"
set -ogq @thm_surface_0 "#a8aecb"
set -ogq @thm_mantle "#d0d5e3"
set -ogq @thm_crust "#c1c9df"
