"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[░▒▓](#a9b1d6)\
$username\
[@](bg:#a9b1d6 fg:#090c0c)\
$hostname\
[](bg:#7aa2f7 fg:#a9b1d6)\
$directory\
[](fg:#7aa2f7 bg:#3b4261)\
$git_branch\
$git_status\
[](fg:#3b4261 bg:#1a1b26)\
\n$character"""

[username]
show_always = true
style_user = "bg:#a9b1d6 fg:#090c0c"
style_root = "bg:#a9b1d6 fg:#090c0c"
format = '[ $user]($style)'

[hostname]
style = "bg:#a9b1d6 fg:#090c0c"
format = '[$hostname ]($style)'
aliases = { "s-bor-vpi151000" = "ssm-webprod 󰯊",
            "s-ssm-vdi151200" = "ssm-webdev ",
            "W-SSM-A096925" = "odemin 󰇅",
            "W-SSM-A096960" = "tsuga 󰇅",
            "rubus" = "rubus 󰇅",
            "picea" = "picea 󰇅",
            "salix" = "salix 󰇅",
            "s-bor-vpa151250" = "ledum 󰒍",
            "s-bor-vpq151251" = "postgres ",
            "lomax" ="lomax 󱝠" }
ssh_only = false

[directory]
style = "fg:#c0caf5 bg:#7aa2f7"
read_only_style = "fg:#c0caf5 bg:#7aa2f7"
read_only = ""
format = "[ $path]($style)[ $read_only ]($read_only_style)"
truncation_length = 6
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:#3b4261"
format = '[[ $symbol $branch ](fg:#7aa2f7 bg:#3b4261)]($style)'

[git_status]
style = "bg:#3b4261"
format = '[[($all_status$ahead_behind )](fg:#7aa2f7 bg:#3b4261)]($style)'
